# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5db41d93463a3fcba67ad6799faa37fb20ba94c08b7d912d5e2e88fc39985fa4aef16c5cdbe78ab7926cce85e4aa707d3287b1ea90f1b253d6a345d908ef496a

test:
  secret_key_base: d779214e86cf58583a4797a4d609a7be1a3afc3a0c1cd46331f367b5338da7337277ba987607ffd79a5e7b1b3583fd7811757f08629e8b1a2575bcc1aa668c0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
